#size: 54
#name: Recipe
## variables
##  regionType = region type to check
##  category = reqs | reagents0 | input0 | output0 | failing | g:groupName
##  $groupName$ the name of the group the item belongs to
#items:
#  prev:
#    index: 3
#  back:
#    index: 8
#  next:
#    index: 5
#  items:
#    index: 9-53
#    # icon: item
#    # name: material name
#    # desc: group name
#    # actions = menu:recipe?category=g:$groupName$
